//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap application_exit {
            get {
                object obj = ResourceManager.GetObject("application-exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete the selected files?.
        /// </summary>
        internal static string Are_you_sure_that_you_want_to_delete_the_selected_files_ {
            get {
                return ResourceManager.GetString("Are_you_sure_that_you_want_to_delete_the_selected_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close all windows?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_close_all_windows_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_close_all_windows_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this bookmark?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_bookmark_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_this_bookmark_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this folder?.
        /// </summary>
        internal static string Are_you_sure_you_want_to_delete_this_folder_ {
            get {
                return ResourceManager.GetString("Are_you_sure_you_want_to_delete_this_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Back_icon {
            get {
                object obj = ResourceManager.GetObject("Arrow_Back_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_Next_icon {
            get {
                object obj = ResourceManager.GetObject("Arrow_Next_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all windows?.
        /// </summary>
        internal static string Close_all_windows_ {
            get {
                return ResourceManager.GetString("Close_all_windows_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delete.
        /// </summary>
        internal static string Confirm_delete {
            get {
                return ResourceManager.GetString("Confirm_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading new image.
        /// </summary>
        internal static string Error_loading_new_image {
            get {
                return ResourceManager.GetString("Error_loading_new_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to load settings.
        /// </summary>
        internal static string Faild_to_load_settings {
            get {
                return ResourceManager.GetString("Faild_to_load_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to decode file..
        /// </summary>
        internal static string failed_to_decode_file_ {
            get {
                return ResourceManager.GetString("failed_to_decode_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set transition image over current image!.
        /// </summary>
        internal static string Failed_to_set_transition_image_over_current_image_ {
            get {
                return ResourceManager.GetString("Failed_to_set_transition_image_over_current_image_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error encountered when accessing the registry settings please restart .
        /// </summary>
        internal static string Fatal_error_encountered_when_accessing_the_registry_settings_please_restart_ {
            get {
                return ResourceManager.GetString("Fatal_error_encountered_when_accessing_the_registry_settings_please_restart_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid filename selected.
        /// </summary>
        internal static string FileBrowser_OpenImporterForm_No_valid_path_selected {
            get {
                return ResourceManager.GetString("FileBrowser_OpenImporterForm_No_valid_path_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  MB.
        /// </summary>
        internal static string FormSettings_UpdateCacheSizeLabel__MB {
            get {
                return ResourceManager.GetString("FormSettings_UpdateCacheSizeLabel__MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files(*.jpg;*.jpeg;*.png;*.gif;*.bmp)|*.jpg;*.jpeg;*.png;*.gif;*.bmp.
        /// </summary>
        internal static string ImageFormatFilter {
            get {
                return ResourceManager.GetString("ImageFormatFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        internal static string Invalid_password_ {
            get {
                return ResourceManager.GetString("Invalid_password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please unlock bookmarks first.
        /// </summary>
        internal static string Please_unlock_bookmarks_first {
            get {
                return ResourceManager.GetString("Please_unlock_bookmarks_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove folder?.
        /// </summary>
        internal static string Remove_folder_ {
            get {
                return ResourceManager.GetString("Remove_folder_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent {
            get {
                object obj = ResourceManager.GetObject("transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Access application settings in registry.
        /// </summary>
        internal static string Unable_To_Access_application_settings_in_registry {
            get {
                return ResourceManager.GetString("Unable_To_Access_application_settings_in_registry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WindowsIcon {
            get {
                object obj = ResourceManager.GetObject("WindowsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
